name: Build Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        projects:
          - allhash
          - containerize
          - cyberchef-standalone
          - elasticdump
          - fakedns
          - fossflow-standalone
          - gopherchain
          - grizz
          - identme
          - mhs
          - oauth2
          - pcap-freshner
          - pebble-cli
          - proxyenv
          - redlineparser
          - sctptunnel
          - siemsend
          - sniplex
          - sockstls
          - spitcurl
          - sshproxy
          - webhookio
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.x'

    - name: Build and release
      uses: wangyoucao577/go-release-action@v1
      env:
        CGO_ENABLED: 0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: '1.25.x'
        project_path: ${{ matrix.projects }}
        asset_name: ${{ matrix.projects }}-${{ matrix.goos }}-${{ matrix.goarch}}
        binary_name: ${{ matrix.projects }}
        ldflags: -s -w -extldflags '-static'
        extra_files: LICENSE README.md
